import { Boat, Review } from '@/types';

export const topRatedBoats: Boat[] = [
  {
    id: '1',
    ownerId: 'owner-1',
    name: 'Pearl of Capri',
    type: 'yacht',
    capacity: 12,
    location: 'Angra dos Reis, RJ',
    pricePerDay: 3450,
    description: 'Experience the pinnacle of maritime luxury aboard the Pearl of Capri.',
    images: ['/images/yacht-card-1.png'],
    rating: 4.9,
    reviewCount: 156,
    length: 26.8,
    cabins: 4,
    crew: 3,
    badges: ['Elite Class', 'Verified Vessel'],
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    ownerId: 'owner-2',
    name: 'Casa Branca',
    type: 'speedboat',
    capacity: 8,
    location: 'Ilhabela, SP',
    pricePerDay: 2800,
    description: 'A sleek modern speedboat for thrilling ocean adventures.',
    images: ['/images/yacht-card-2.png'],
    rating: 4.8,
    reviewCount: 89,
    length: 15.2,
    cabins: 2,
    crew: 2,
    badges: ['Verified Vessel'],
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    ownerId: 'owner-3',
    name: 'Azure Diamond',
    type: 'yacht',
    capacity: 20,
    location: 'Búzios, RJ',
    pricePerDay: 5500,
    description: 'A magnificent mega-yacht for the most exclusive experiences at sea.',
    images: ['/images/yacht-card-3.png'],
    rating: 5.0,
    reviewCount: 42,
    length: 45.0,
    cabins: 6,
    crew: 5,
    badges: ['Elite Class', 'Verified Vessel', 'Premium'],
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    ownerId: 'owner-4',
    name: 'Veleiro Aura',
    type: 'sailboat',
    capacity: 6,
    location: 'Paraty, RJ',
    pricePerDay: 1950,
    description: 'The classic sailing experience for the adventurous spirit.',
    images: ['/images/yacht-card-4.png'],
    rating: 4.7,
    reviewCount: 118,
    length: 12.5,
    cabins: 2,
    crew: 1,
    badges: ['Verified Vessel'],
    createdAt: '2024-04-05',
  },
];

export const featuredCharters: Boat[] = [
  {
    id: '5',
    ownerId: 'owner-5',
    name: 'Serene Voyager',
    type: 'catamaran',
    capacity: 10,
    location: 'Fernando de Noronha, PE',
    pricePerDay: 4100,
    description: 'An elegant catamaran for peaceful ocean voyages.',
    images: ['/images/charter-1.png'],
    rating: 4.9,
    reviewCount: 73,
    length: 18.0,
    cabins: 3,
    crew: 2,
    badges: ['Elite Class'],
    createdAt: '2024-05-01',
  },
  {
    id: '6',
    ownerId: 'owner-6',
    name: 'Azure Horizon',
    type: 'yacht',
    capacity: 12,
    location: 'Florianópolis, SC',
    pricePerDay: 2800,
    description: 'A luxury yacht with world-class amenities.',
    images: ['/images/charter-2.png'],
    rating: 4.6,
    reviewCount: 95,
    length: 22.0,
    cabins: 4,
    crew: 3,
    badges: ['Verified Vessel'],
    createdAt: '2024-06-15',
  },
  {
    id: '7',
    ownerId: 'owner-7',
    name: 'Nautic Thrill',
    type: 'jetski',
    capacity: 2,
    location: 'Guarujá, SP',
    pricePerDay: 1150,
    description: 'High-speed jet ski for water sports enthusiasts.',
    images: ['/images/charter-3.png'],
    rating: 4.8,
    reviewCount: 210,
    createdAt: '2024-07-20',
  },
];

export const sampleReviews: Review[] = [
  {
    id: 'r1',
    boatId: '1',
    userId: 'u1',
    userName: 'James D.',
    rating: 5,
    comment:
      'Uma experiência absolutamente deslumbrante! O Azure Horizon é ainda mais bonito pessoalmente. O Capitão Marco e sua equipe foram excepcionais, atenciosos a cada detalhe.',
    createdAt: '2024-09-15',
  },
  {
    id: 'r2',
    boatId: '1',
    userId: 'u2',
    userName: 'Sarah Miller',
    userAvatar: '',
    rating: 5,
    comment:
      'A fuga perfeita da cidade. Reservar através do Boatzy foi simples e nos deu muito mais tranquilidade. O iate está em perfeitas condições e o lounge interno é extremamente confortável.',
    createdAt: '2024-10-02',
  },
];

export const moments = [
  {
    title: 'Wellness at Sea',
    image: '/images/moment-wellness.png',
    description: 'Relaxe em alto mar com experiências de spa e yoga',
  },
  {
    title: 'Mergulho & Diving',
    image: '/images/moment-diving.png',
    description: 'Explore recifes de coral e vida marinha',
  },
  {
    title: 'Gastronomia Gourmet',
    image: '/images/moment-gourmet.png',
    description: 'Jantares exclusivos com vista para o mar',
  },
  {
    title: 'Praias Secretas',
    image: '/images/moment-secret.png',
    description: 'Descubra paraísos escondidos',
  },
];
